# Site
name: 'Telegram 游戏中心'
description: 'Telegram 小游戏中心，为你收集最好玩最赚钱的小游戏'
logo: 'assets/images/logo.png'
favicon: 'assets/images/favicon.ico'
baseurl: '/'
disqus: 'demowebsite'
email: 'huangdh3@gmail.com'

include: ["_pages"]
permalink: /:title/

# Plugins
plugins: 
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-seo-tag
  
authors:
    sal:
      name:           游戏爱好者
      avatar:         assets/images/avatar1.jpg
      bio:            "游戏爱好!"
      email:          huangdh3@gmail.com

    jane:
      name:           资深游戏分享者
      avatar:         assets/images/avatar2.jpg
      bio:            "资深游戏分享!"
      email:          huangdh3@gmail.com
 
# Defaults
defaults:

  # all posts
  - scope:
      path: "_posts"
    values:
      layout: post
      author: sal
      avatar: assets/images/avatar1.jpg
      
  # all pages
  - scope:
      path: "_pages"
    values:
      layout: page
      
# Syntax
markdown: kramdown
highlighter: rouge

# Paginate
paginate: 10



# Exclude metadata and development time dependencies (like Grunt plugins)
exclude: [README.markdown, package.json, grunt.js, Gruntfile.js, Gruntfile.coffee, node_modules]